### ISSUE TITLE
suggestion rappel memoire en mode VFO

### ISSUE THREAD

**Issue by dbrot** [armel/uv-k5-firmware-custom#103]
Bonjour

A l'instar de ce qui est fait dans la partie fm broadcast, serait-il possible , en mode VFO, d'afficher le numéro de la mémoire affectée à une fréquence (si c'est le cas)

Merci
Cordialement
Denis

**Comment by armel** [comment]
Bonsoir Denis,

Je comprends l'idée, mais j'ai un peu peur coté ressources. Ca voudrait dire qu'en mode VFO, il faudrait systématiquement regarder si la fréquence en cours est éventuellement une fréquence déjà enregistrée et mémorisée. Et si oui, afficher le numéro du canal mémoire.

Je peux regarder à l'occasion, mais je crains le pire en terme de ressources et je m'interroge tout de même un peu sur l'intérêt réel (même si je l'entrevois).

73'

Armel F4HWN.

**Comment by dbrot** [comment]
Je m'en doutais un peu de ce souci au niveau de la conso ressources. Le but était de ne pas enregistrer 2 (ou plus) fois la même fréquence dans les mémoires , mais ça peut se régler autrement , juste avec un peu d'organisation  :-)

Bonne soirée
Denis

**Comment by armel** [comment]
Oui Denis, c'est bien ce que j'avais en tête.
Je regarderais à l'occasion, ca reste intéressant :)

Armel F4HWN.

**Comment by f1ixx** [comment]
Bonjour

Comme de temps a autre, je mets mon grain de sel.
Et si la verif etait faite uniquement a l'enregistrement? [ChSave] 
On fait une verif et bip bip - display : Freq in Mxxx

73's

Boris

**Comment by armel** [comment]
Bonsoir Boris,

Ce serait déjà plus économique en terme de ressources, tu as raison.
Je regarderais, merci.

Armel F4HWN.

**Comment by lapinos03** [comment]
Et si on a envie de mémoriser 2 relais (distants) qui ont la même fréquence ? Pour ceux qui sont nomades...

**Comment by f1ixx** [comment]
Bonjour
J'ai pas regarde pour cette fonction. Apres a voir en terme d'octets (c'est le nerf de la guerre
avec notre uv-k5)
Lorsqu'on fait un save, si la frequence est deja en memoire, on affiche : use in Mxxx, save?
Si on fait <code>[MENU]</code> : ca sauve dans le canal memoire choisie.
Si on fait <code>[EXIT]</code>, on resort sans rine faire.

je lance juste des idees et loin de moi a dire que c'est la solution.

73's
Boris

**Comment by armel** [comment]
Bonjour,

@lapinos03 Le plan de bande IARU est là pour ca. Par exemple, sur le [144](https://thf.r-e-f.org/plans_des_bandes/144.htm), tu verras qu'une portion de la bande est réservée aux entrées de relais et une autre partie est réservée aux sorties de relais. En pratique ca donne quoi ? Et bien ca donne une [liste de 16 fréquences de relais](https://amat-01.r-e-f.org/p13-les-relais-fr.htm) avec shift (ou offset) que l'on appelle dans notre jargon R0, R0x, R1, R1x...R7, R7x.

Par exemple, 
- le R0 est sur 145.0000 / 145.6000
- le R1 est sur 145.0125 / 145.6125
- etc.

Et on trouve un R0 sur Alès (30), Guéret (23), La Rochelle (17), etc. il doit y en avoir une demie douzaine en France. 

À ce titre, la bonne pratique (et c'est ce que je fais dans mes canaux mémoire), c'est de mémoriser les 16 fréquence de relais de R0 à R7x. Et t'es tranquille. Alors oui, d'un relais à l'autre, le mode de déclenchement peut changer (CTCSS, DCS ou 1750), mais ca se modifie à la volée très rapidement depuis le poste. 

73'

Armel F4HWN.

**Comment by armel** [comment]
Pour @f1ixx, vérifier qu'une fréquence est déjà présente dans la liste des mémoires, ca coûte entre 600 et 700 octets... Tu vois le drame ? :) 

73'

Armel F4HWN.

**Comment by f1ixx** [comment]
@armel, oui carrement 😱

**Comment by f1ixx** [comment]
A voir si ca fonctionne, si ca n'ajoute pas des bugs etc etc.
Attention, ca risque de pique les yeux.

Dans ui/menu.c vers la ligne 1100
<pre>
	if ((UI_MENU_GetCurrentMenuId() == MENU_RESET    ||
	     UI_MENU_GetCurrentMenuId() == MENU_MEM_CH   ||
	     UI_MENU_GetCurrentMenuId() == MENU_MEM_NAME ||
	     UI_MENU_GetCurrentMenuId() == MENU_DEL_CH) && gAskForConfirmation)
	{	// display confirmation
		char *pPrintStr = (gAskForConfirmation == 1) ? "SURE?" : "WAIT!";
		UI_PrintString(pPrintStr, menu_item_x1, menu_item_x2, 5, 8);
	}
</pre>

devient
<pre>	if ((UI_MENU_GetCurrentMenuId() == MENU_RESET    ||
	     UI_MENU_GetCurrentMenuId() == MENU_MEM_CH   ||
	     UI_MENU_GetCurrentMenuId() == MENU_MEM_NAME ||
	     UI_MENU_GetCurrentMenuId() == MENU_DEL_CH) && gAskForConfirmation)
	{	// display confirmation

#if 1
		sprintf(String, "%s", (gAskForConfirmation == 1) ? "SURE?" : "WAIT!");
		if (UI_MENU_GetCurrentMenuId() == MENU_MEM_CH)
		  {
			  for(char i=0; i<200; i++)
			    {
					if (SETTINGS_FetchChannelFrequency(i) == gEeprom.VfoInfo[ gRxVfoIsActive ? gEeprom.RX_VFO : gEeprom.TX_VFO].pTX->Frequency)
						{
							sprintf(String, "M%03d SURE?", i);
							break;
						}
				}
		  }
		UI_PrintString(String, menu_item_x1, menu_item_x2, 5, 8);
#else
		char *pPrintStr = (gAskForConfirmation == 1) ? "SURE?" : "WAIT!";
		UI_PrintString(pPrintStr, menu_item_x1, menu_item_x2, 5, 8);
#endif
</pre>

Possible que cela ne soit pas complet, oublie des fonctions, etc etc
pour m'aide a comprend, me dire les bugs et horreurs que j'ai ecrit.

73's

**Comment by armel** [comment]
Bonsoir Boris,

Merci à toi. C'est pas mal, mais j'aurais néanmoins 2 remarques.
Dans la suite, je vais prendre la QRG 125.000,00 qui n'est affectée à aucune mémoire dans mon transceiver. 

-----

1 - l'indice du canal que tu affiches via `sprintf(String, "M%03d SURE?", i);` n'est pas le bon. Il faudrait l'incrémenter de 1. Donc faire plutôt `sprintf(String, "M%03d SURE?", i + 1);` 

Etape 1 - tu enregistres, via le menu ChSave, une QRG, disons 125.000,00 sur le canal 180,
Etape 2 - tu enregistres à nouveau, ca t'indique **M179 Sure?** alors que tu es sur le canal CH-180,

Au passage, il semble inutile de rappeler que l'on va ré-écrire le canal 180 sur lui même. Ce que l'on veut surtout, c'est éviter les doublons. Donc éviter d'affecter la QRG 125.000,00 à un autre canal, par exemple le 190. On peut évidement s'en sortir facilement en complétant ton `if (SETTINGS_FetchChannelFrequency(i)...`

-----

2 - ca peut être source de comportements douteux. 

Et c'est là que ca se gate...

Etape 1 - tu enregistres, via le menu ChSave, une QRG, disons 125.000,00 sur le canal 180,
Etape 2 - tu supprimes, via le menu ChDel, ce canal 180.
Etape 3 - tu enregistres, via le menu ChSave, toujours la même QRG 125.000,00, mais cette fois sur le canal 190 (donc un autre indice de canal).

Et ca va d'indiquer à nouveau **M179 Sure?** alors que tu l'as supprimé, comme s'il existait toujours.

Bref, il est évidement possible d'éviter tout cela, mais il faut ajouter d'autres rustines et l'occupation mémoire va s'envoler. La question est donc : l'ajout de cette fonctionnalité en vaut elle la chandelle ? J'y suis moyennement favorable.

Pour finir, au chapitre du détail, on peut améliorer ta boucle

`
for(char i=0; i<200; i++)
`

Par,

`
for (uint8_t i = 0; IS_MR_CHANNEL(i); i++)
`

73'

Armel F4HWN.

**Comment by f1ixx** [comment]
Bonjour Armel

Merci pour ces explications et remarque.
Pour le decalage je l'ai vu apres mon poste, j'avais deja ajoute le +1.
Effectivement, y'a encore a regarde, j'ai fais quelques teste mais pas assez ;-)

Pour les memoire effacer, on doit pouvoir corrige ca au moment de l'effacement.
Pour m'amuse je vais regarde. Mais faut deja joue des coudes pour que ca rentre ;-)
Et des choses etranges arrive quant on compile.

Grand merci a vous pur ce retour

Boris

**Comment by f1ixx** [comment]
Comme d'hab, on corrige 1 bug et on en ajoute 4 ;-)

Au lieu d'affiche le canal, on affiche celui qui est trouver.
vers la ligne 1115, Je change le <pre>sprintf...</pre> par :
<pre>
	gSubMenuSelection = i;
	gIsInSubMenu = false;
	gAskForConfirmation = 0;
</pre>

et dans le fichier : setting.c
vers la ligne 818
<pre>
if (!keep) {
	// clear/reset the channel name
	SETTINGS_SaveChannelName(channel, "");
	}
</pre>
devient
if (!keep) {
	// clear/reset the channel name
	SETTINGS_SaveChannelName(channel, "");
	memset(state, 0xFF, sizeof(state));
	EEPROM_WriteBuffer(channel*16, state);
}</pre>

Voila, si ca interesse quelqu'un et que j'ajoute pas trop de bug ;)
J'arrete ici les modifications, je vais tante de faire un github pour ma version ultraBeta.

Merci pour vos commantaires et aides 
73's

Boris
