### ISSUE TITLE
SI4732-A10

### ISSUE THREAD

**Issue by JustFun3D** [armel/uv-k5-firmware-custom#111]
Is it planned that there will be a version that supports the SI4732-A10?

Or can the 10,20,40,60,80,m band range be included?

73, DL9CL

**Comment by armel** [comment]
About SI4732 support, no, this is not planned.
The internal BK4819 covers frequency bands from 18MHz to 630MHz and 760MHz to 1300MHz.
That's all.

73'

Armel F4HWN.
