### ISSUE TITLE
Compander should not save upon selection

### ISSUE THREAD

**Issue by prokrypt** [armel/uv-k5-firmware-custom#122]
Since the compander option is grouped with the other channel settings, it would be logical to assume that it does not save to the channel automagically.

@ [In app/menu.c](https://github.com/armel/uv-k5-firmware-custom/blob/829956c0400da61863321884a7d4f19c79775cc6/app/menu.c#L654) line 654:
`SETTINGS_UpdateChannel(gTxVfo->CHANNEL_SAVE, gTxVfo, true, false, true);`
should be changed to
`SETTINGS_UpdateChannel(gTxVfo->CHANNEL_SAVE, gTxVfo, true, false, false);`

Same for the ScAdd menu items, but in that case automagic saving makes sense, as there is no need (and no way) to "preview" the changes. Perhaps they should be moved down past the channel settings (right before SList) to indicate they don't need manual saving...

**Comment by prokrypt** [comment]
Just a little quirk with the change I suggested. It seems the compander setting does not reset back to the original setting when you change channels and then go back. Looks like it may need some other change(s) to match the behavior of the other settings...

**Comment by armel** [comment]
The real question would be whether the compander function is actually used by anyone. I never use it. And you ? 🤗

**Comment by prokrypt** [comment]
I use it every now and then, which is how I found the "bug"... Although it's no big loss for me if it's gone, I know lots of radios (including very cheap ones) have this function, and it does make long distance communication more clear.

**Comment by KDMcMullan** [comment]
I'd proposed removing it to free up program memory. This is a 5W HT, and I'd guess 80% of the user base are non-hams wanting to use it as a family walkie-talkie, or listen to airband. I respect that the three of us are hardly "representative", so I'm prepared to be corrected on this, but if anyone was taking the feature seriously, they'd be on here looking down the feature list and making suggestions.

**Comment by armel** [comment]
Compander is an attribute specific to each channel. I won't change anything here 😌
