### ISSUE TITLE
bug lors du scan ?

### ISSUE THREAD

**Issue by stephane-rib** [armel/uv-k5-firmware-custom#123]
Bonjour Armel,
j'ai remarqué un comportement bizarre lors du scan des mémoires (appui long sur *SCAN), en mode DW ou DWR (dual-watch) le scan se passe normalement en gardant le double affichage; en revanche en mode XB (cross-band) il passe automatiquement l'affichage en mode simple VFO, puis revient en double affichage lorsque le scan s'arrête, bug ou comportement normal?
Merci encore pour ton investissement
Stéphane

**Comment by prokrypt** [comment]
I would think this is the correct behavior. If there were 2 VFOs on XB while scanning, it would either not work correctly or be extremely confusing.

**Comment by armel** [comment]
Bonsoir Stéphane,

C'est tout à fait normal en mode Cross Band. 

73'

Armel F4HWN

**Comment by stephane-rib** [comment]
merci
désolé pour le dérangement...

**Comment by armel** [comment]
Personne n'a été dérangé :) 
Je clôture cette issue.

73'

Armel F4HWN
