### ISSUE TITLE
"208" codes DCS

### ISSUE THREAD

**Issue by DrAetheria** [armel/uv-k5-firmware-custom#125]
Alors voici comment j'ai fait:
TxDCS=0
F2
Et pop, 208.
Ou juste taper 208

Mis entre guillemets car il affiche 208 mais il a juste double le truc.

**Comment by armel** [comment]
Il va falloir être plus explicite...
TxDCS permet de paramétrer un code DCS en émission.
Entrer 208 au clavier permet de sélectionner directement le code D 754 I (DCS inversé), ce qui est normal.
Quant à l'appui sur F2, il est sans effet chez moi (autre que jouer l'action associée évidement, en l'occurence, allumer la LED pour moi).
