### ISSUE TITLE
suggestion: "switch rx mode" should be a binary toggle

### ISSUE THREAD

**Issue by prokrypt** [armel/uv-k5-firmware-custom#126]
This is only my opinion: the "switch rx mode" shortcut would be more convenient if it only switches between "Main Only" and whatever mode you have saved. If you have selected "Main Only" in settings then it can switch through all the modes.

**Comment by KDMcMullan** [comment]
Actually, I initially thought "but there are multiple Rx modes". However, the ability, with a single button,  to toggle between "Main Only" and "Dual Rx" would be very useful.

**Comment by armel** [comment]
Take a look at the MAINL ONLY action, which I've just added to v2.8.
Enjoy.

Armel F4HWN.
