### ISSUE TITLE
bug: backlight level 1 and 2 do not turn on backlight

### ISSUE THREAD

**Issue by prokrypt** [armel/uv-k5-firmware-custom#131]
known issue when pwm frequency is set too high. perhaps something can be adjusted to put the brightness scale back to normal.

**Comment by armel** [comment]
I know, it's not perfect, but it will be hard to fix.

The choice is as follows: 

- low frequency for PWM = noise under modulation, but **there is a visible diff** between backlight levels 1 and 2 
- high frequency for PWM = no noise under modulation, but **there is no visible diff** between backlight levels 1 and 2 

The maximum frequency with a visible diff between backlight level 1 and 2 is around 7 kHz... But this frequency is audible (if your young...)

My choice is quickly made.

**Comment by prokrypt** [comment]
Random idea: how about increasing the pwm frequency only when transmitting?
Also, have you tested other frequencies? 12kHz-18kHz might not be very audible over radio tx. 25kHz seems a bit overkill to me.

**Comment by zardoz99** [comment]
Would this not cause a visual problem if you were running at a low number in the brightness scale. When you transmitted, it would make the display dim and you might be led to believe that there was a battery problem. It might be confusing for users.
----------------------------------------

*From: *prokrypt ***@***.***>
*To: *armel/uv-k5-firmware-custom ***@***.***>
*CC: *Subscribed ***@***.***>
*Date: *Jun 13, 2024 11:46:09 p.m.
*Subject: *Re: [armel/uv-k5-firmware-custom] bug: backlight level 1 and 2 do not turn on backlight (Issue #131)

**Comment by armel** [comment]
Agreed with @zardoz99 

Note that the human audible spectrum extends from 20 Hz to 20 kHz.
As I said, if the PWM frequency is above 7 kHz, there's no visible difference between backlight levels 1 and 2.
PWM frequency needs to be under 7kHz so... plain in human range.

Armel F4HWN.

**Comment by prokrypt** [comment]
As of right now, there is no difference between levels 0, 1, and 2... I'm not sure if there is a hardware thing though as I have a KSUN UV60D. I might have some experimentation with it a little later on.

**Comment by prokrypt** [comment]
I just did a simple test with a few different pwm values and an rtlsdr dongle and there was no difference in the squeal.
I'm not sure if the frequency is right as I haven't calibrated my SDR, but it seems there are two tones, one at ~3.750k and one at 7.5k. What is obvious though is that they remain relatively unchanged between different values. 
![squealy](https://github.com/armel/uv-k5-firmware-custom/assets/1832555/5fe2c3d9-e94f-4b7c-a25e-7c1d02a5c403)

**Comment by prokrypt** [comment]
And while I'm at it, I decided to test another uv60d with LOSEHU's firmware, and some cheap "frs" radio I had.
![comp](https://github.com/armel/uv-k5-firmware-custom/assets/1832555/0ed75b39-2a2f-4e64-b8fe-857b188d2510)

**Comment by armel** [comment]
Fixed in next release.
