### ISSUE TITLE
Unable to flash via UVtools

### ISSUE THREAD

**Issue by tk5ep** [armel/uv-k5-firmware-custom#135]
Hi,

When trying to flash via the suggested UVtools web page, I get the following error :

Connecting to the serial port...
Radio in flash mode detected.
Unusual error occured, check console for details.

Any guess on what's going wrong ? I can read the radio with Chirp, so connections are OK.

73, Patrick

**Comment by armel** [comment]
Hi Patrick,

Which browser do you use?
Have you checked the console for details ?

Armel F4HWN.

**Comment by tk5ep** [comment]
Hi Armel,
Thanks for the answer.
Strangely, back home I tried again and it worked flawlessly!

I should tried to reboot the computer before writing this issue. I did close/reload the UVtools page as well as the UV-K5, but this didn't help
Browser is Chrome.

Now, I've to get familiar with your SW. 

Sorry for the bandwidth.
73 Patrick

**Comment by armel** [comment]
Hi Patrick,

No problem. I'm closing this issue.
Have fun with this firmware.

Armel F4HWN.
