### ISSUE TITLE
bug: pretty annoying quirk in spectrum

### ISSUE THREAD

**Issue by prokrypt** [armel/uv-k5-firmware-custom#151]
The first bar/frequency is always at 0 (skipped?), and the last frequency is off screen (still jumps to that frequency if it's active).

Extra interesting quirk: the first bar displays if you blacklist all the other frequencies (easier to do @ 16x)

**Comment by prokrypt** [comment]
I found it. `if(blacklistFreqs[i] == idx)` in `static bool IsBlacklisted(uint16_t idx)` will return true when idx is 0 :melting_face:

**Comment by armel** [comment]
Spectrum analyzer is a sort of project in the project. It works decently enough. 
I won't fix it for the moment. 
But feel free to PR 😌

**Comment by armel** [comment]
Fixed in next release. Thank you.
