### ISSUE TITLE
bug: temporary scan list selection gets saved when switching vfo or using lock

### ISSUE THREAD

**Issue by prokrypt** [armel/uv-k5-firmware-custom#157]
happens because `gRequestSaveSettings` is set in `COMMON_KeypadLockToggle()` and `COMMON_SwitchVFOs()`

unsure of how to fix...

maybe have a gCurrentScanlist or something rather than setting gEeprom.*

and the same thing happens with squelch via f+up/down shortcut.

**Comment by armel** [comment]
Does anyone have a problem with that?
