### ISSUE TITLE
Mic Gain

### ISSUE THREAD

**Issue by KDMcMullan** [armel/uv-k5-firmware-custom#166]
Is it possible to allow further increase Mic Gain? I have +15.1dB as the maximum. Perhaps that's the hardware max limit?
Thanks.

**Comment by armel** [comment]
According to the BK4819 datasheet, 

```
REG_7D<4:0> 0x10 MIC Sensitivity Tuning.
0x00=min; 0x1F=max; 0.5dB/step
```

In short, 0x1F = 31 is the max value. This is 0.5dB/step, **so 31/2 ~ 15 dB** (max value...).

Armel F4HWN

**Comment by KDMcMullan** [comment]
Thank you.
