### ISSUE TITLE
Feature request: Fast scanning such as that implemented in Kamilsss655 firmware

### ISSUE THREAD

**Issue by SutliffeProductions** [armel/uv-k5-firmware-custom#169]
I feel like this is a direct not possible, but having the ultrafast scanning feature of the Kamilsss655 firmware would be amazing, especially now there is a 3rd scan lists i am much more tempted to fill over 100 memory channels, which takes a while to scan. if it is al all possible that would be amazing, I'm loving this firmware so far.

**Comment by prokrypt** [comment]
one way to do this: fewer screen updates during scanning.
another way: maybe have a dedicated scanning function that only reads frequencies from eeprom (is that how it's done?), then only read other channel-specific settings when squelch is broken.

**Comment by armel** [comment]
duplicate #31
