### ISSUE TITLE
"Power" menu value is not saved.

### ISSUE THREAD

**Issue by vadimostanin** [armel/uv-k5-firmware-custom#171]
"Power" menu option is saved, and after turn off, turn on, it restore old value.

**Comment by armel** [comment]
The reason is : in memory mode, power is a "per channel" parameter. You can change it from the radio. But if you want this change to persist (after changing channel, restarting the pocket, etc.), you need to save the memory channel again (via menu 16/64, ChSave).

Regards,

Armel F4HWN.

**Comment by vadimostanin** [comment]
I see.
Thank you.
