### ISSUE TITLE
Version voxless Touche 5 appui long

### ISSUE THREAD

**Issue by f4axk** [armel/uv-k5-firmware-custom#182]
slt Armel

J'ai testé la version voxless , l'appui long sur la touche 5 pour le déplacement canal mémoire dans une liste ne fonction pas ,
fonctionne très bien sur la version Bandscope.

73s laurent F4AXK

**Comment by armel** [comment]
Bonjour Laurent,

Je regarderais rapidement, mais je ne compte pas maintenir cette version et donc passer du temps dessus.
Supprimer le vox permettait de faire rentrer le reste, mais c'est du temporaire... De toutes façons, il faudra choisir tôt ou tard.

Armel F4HWN

**Comment by armel** [comment]
Fixé dans la prochaine release.
