### ISSUE TITLE
scanlist change in WITHOUT VOX version

### ISSUE THREAD

**Issue by Jekko76** [armel/uv-k5-firmware-custom#183]
in the firmware with bandscope and without vox version, long press "5" on a channel doesn't change the scanlist.
in the firmware with bandscope and without fm radio version, long press "5" on a channel does change the scanlist correctly.
Thanks

**Comment by armel** [comment]
With the voxless version, simply use long press "7".

**Comment by Jekko76** [comment]
the "7" key works like a charm! :) Thank you Armel!

**Comment by armel** [comment]
You're welcome :)

**Comment by MrMinecraft97** [comment]
Will this be fixed in a future version or noted in the docs? Any other features like this?
