### ISSUE TITLE
bursts of noise on spectrum with memory name display feature

### ISSUE THREAD

**Issue by prokrypt** [armel/uv-k5-firmware-custom#190]
I think it happens when it scans through all the memory channels on each screen redraw. I suggest you cache the name and rescan only when the frequency has changed. It takes a bit of time to scan through the channels, so fixing this issue would also make the listen interface more responsive (right now the STILL mode tends to ignore user input) and reduce the squelch tail (though it's still pretty long)

https://github.com/user-attachments/assets/fba70a4d-101b-413d-9d6d-992674966aed

**Comment by armel** [comment]
This noise is certainly not linked to the display of the channel name on the screen, but more likely to a surrounding AND periodic disturbance.

**Comment by prokrypt** [comment]
It only happens on the firmware with the FM feature disabled.

**Comment by prokrypt** [comment]
Example of the input lag:

https://github.com/user-attachments/assets/1026fe29-57fa-4016-ace0-217b8953cdb8

**Comment by prokrypt** [comment]
I fixed the problem, but don't know if my method is ideal. I'll leave it to you to implement whichever way you like:
![diff](https://github.com/user-attachments/assets/3912c626-a2c9-40c4-a417-1b817d1fd919)

**Comment by prokrypt** [comment]
It only works on the non-fm-broadcast firmware. On my own voxless fork, I have it display only an "M" to save space from looking up channel names.

**Comment by jepotter224** [comment]
I have the voxless v 3.2 loaded and I never see an M with a memory channel is hit.....not sure why?

**Comment by armel** [comment]
And of course, you did read the description? About VoxLess version : VOX, Audio bare, Air Copy support and **new bandscope evolutions since v3.0 were been removed**...
If you want this feature, use bandscope version :)

**Comment by jepotter224** [comment]
Thank you for the clarification and direction for finding this feature......FYI - appreciate all you work!

**Comment by armel** [comment]
@jepotter224 you're welcome 🤗
