### ISSUE TITLE
"Scan Range" not working with v3.0 ?

### ISSUE THREAD

**Issue by goopaga** [armel/uv-k5-firmware-custom#191]
I've tried everything but I'm not able to turn on ScnRng while in VFO for both A and B VFOs.
Long press key 5 doesn't activate Scan Range with v3.0

Just a check to understand if it's a regression or it's just my radio.

Thanks '73 de IU4MJW

**Comment by prokrypt** [comment]
Probably has to do with vox being disabled?
Try 7 instead of 5. Supposedly it will be fixed in the next update.

**Comment by MrMinecraft97** [comment]
That seems to be it. I have the no-vox version too and holding 7 instead of 5 works.
