### ISSUE TITLE
Double beep for non-existent channel, changing the channel with the arrows while entering the digits

### ISSUE THREAD

**Issue by mrkusypl** [armel/uv-k5-firmware-custom#192]
### The modified codes below is based on the previous fix (#175)

During use, I noticed that the existence of the channel is checked every time a digit is entered. 

For example, suppose we have channel **35** stored, but channel **3** is empty. Entering the digit **3** will trigger a beep indicating that there is no channel **3** even though our intention is not to go to channel **3**. The timeout is still in progress, so pressing **5** will go to channel **35** which exists. I have made the beep appear after the timeout has stopped (for one-digit and two-digit numbers). The problem does not appear with three-digit numbers, because there is no timeout there.

Modified code: 6820b0a0b4c2ace75c4272eaef5ac488a8e71d69

https://github.com/armel/uv-k5-firmware-custom/assets/110433144/8494f95f-2371-40a9-98cf-bc26c007fe63

Also, I added that when changing the channel by entering digits, using the arrows during the timeout will change the channel relative to the channel entered by the digits (previously, using the arrows triggered a beep).

Modified code: 53d63d8d922a6254971868750a0dbe9d3990f34b

https://github.com/armel/uv-k5-firmware-custom/assets/110433144/13fa6961-9f32-4680-82ce-52422482c91a

I also managed to save **8 bytes**.

**Comment by armel** [comment]
Hello,

Ok for the first improvement. It sounds good to me. I [added](https://github.com/armel/uv-k5-firmware-custom/commit/1260bc8fb209971b082c0cbc563d493509f820a0) it to the next release. 
About the second one, I'm less interested. 

Thank you 🙏🏻

Armel F4HWN.

**Comment by armel** [comment]
Hello, 

Please, take a look at issue #194 if you have time :) This is probably a regression bug due to your patch. 

I understand that if you are on channel 50, switch to channel 120 and turn off the K5, you will return to channel 50 if you restart it. The problem seems to be only if you move on a channel > 100.

Regards,

F4HWN.
