### ISSUE TITLE
List scanning

### ISSUE THREAD

**Issue by Thijss81** [armel/uv-k5-firmware-custom#193]
List scanning. For example set scanlist2 to start on channel 50. After sure? And menu to confirm. It's sets itself back to the setting it was. Same for Slist1 and Slist3? 

Hope you can fix this.

Thnx!

**Comment by armel** [comment]
Sorry, I don't understand.
SList1 is used to list channels assigned to scan list 1.
SList2 is used to list channels assigned to scan list 2.
And SList3 is used to list channels assigned to scan list 3.

That's all.

**Comment by armel** [comment]
No news... I close this issue.

**Comment by Thijss81** [comment]
Sorry for my late reaction.

My sincere apologies! I will first do a better job of figuring things out instead of claiming unjustified problems. I enjoy your firmware, thank you! 

Have a nice day

With regards,

Matthijs
