### ISSUE TITLE
Saved channel issue

### ISSUE THREAD

**Issue by lohtse** [armel/uv-k5-firmware-custom#194]
Since 1260bc8 (Branch is feature_update_v3)   It nolonger remebers what channel I changed too at switch on... Always defaults to the last ones I had been using when was on 3d59dad   
 Eg with ver 3d59dad    channeal was 121 and 122..   _
Since  1260bc8 change channels too 098 1nd 099

Trun off radio and channels are now back to 121 and 122
Change again   turn off an turn on and they are 121 and 122 again

Other than your commitments nothing has actualy changed...

Hope you understand

**Comment by armel** [comment]
Hi,

Ok, it's probably a regression bug.
I'll take a look with @mrkusypl :)

Thank you,

Armel.

**Comment by mrkusypl** [comment]
Interesting... I'll see what I can do about it.

**Comment by mrkusypl** [comment]
It seems that after entering three digits, the function that saves the current channel to memory is not called. After typing one or two digits and waiting a timeout, the function calls correctly.

Just added `SETTINGS_SaveVfoIndices()` for three digits and everything works as expected.

Modified code: 814a4bcd25264a0a6b64037ddcba03181e4fba1c

**Comment by armel** [comment]
Sounds good to me. I [added](https://github.com/armel/uv-k5-firmware-custom/commit/f7084f7c3d5aecefea8ca2f4da4218fe17480641) it. 
Thank you @mrkusypl  👍🏼
