### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by rob-spotter** [armel/uv-k5-firmware-custom#208]
Nice work on this Firmware. Would it be possible to add a feature like the IJV FW when you hold down the A/B button for an extended amount of time to switch the current selected channel into single channel mode vs duel mode then back to duel mode if in single channel mode with the same A/B extended button press sequence. I love this FW, but going to the menu to do it, is kind of a pain. It would be a great addition if it can be done easily. Thank you so much! 😊

**Comment by armel** [comment]
Thank you.

Take a look at MAIN ONLY action. That's exactly what this action does. And you can assign it to the F1 (LONG or SHORT), F2 (LONG or SHORT) or M (LONG) key.

**Comment by armel** [comment]
Those programable button settings ARE in the Chirp driver :)
![Action](https://github.com/user-attachments/assets/8edc6e35-38c9-401a-b8f9-3bfaa4a83468)
