### ISSUE TITLE
No CW support?

### ISSUE THREAD

**Issue by londresarthur** [armel/uv-k5-firmware-custom#221]
The information is not very clear: does this firmware support CW? In this case, pure CW, without modulation, just the carrier.

**Comment by londresarthur** [comment]
edit1: it would be a very interesting implementation to do along with lower bandwidth options

**Comment by armel** [comment]
Ok. This firmware does not support CW and there are no plans to add it.

**Comment by londresarthur** [comment]
OK thanks. And is there manual gain control implemented? I really like this function in IJV, but Fabrizio doesn't seem to want to open source it so I can understand how he implemented it.

**Comment by armel** [comment]
Manual gain control is possible only from the [Spectrum analyzer](https://github.com/armel/uv-k5-firmware-custom/wiki/Spectrum-analyzer#spectrum-sweep-screen).

**Comment by Midnight-Cowboy** [comment]
Hi Armel, 
Is it possible to move the LNA settings outside the spectrum analyzer?

**Comment by armel** [comment]
Hi @Midnight-Cowboy,

It's possible but with many modifications. I'm not sure I want to do it.

**Comment by Midnight-Cowboy** [comment]
Maybe put this in a separate module and sacrifice something when compiling it yourself? For example, I don’t understand why the rx/tx timer is needed, and I could easily do without them.

**Comment by armel** [comment]
@Midnight-Cowboy RX/TX timers are useful when using certain radio networks with TOTs. Second, it's not a memory issue... as I said, moving the LNA settings out of the spectrum analyzer is a huge challenge. And I'm not sure I want to do it. And above all, I don't have the time right now.

**Comment by Midnight-Cowboy** [comment]
it's a pity...

**Comment by armel** [comment]
@Midnight-Cowboy No, it's not a pity. My firmware is full open source. You can try to make this mofication and share it with the community if you wish 👍🏼 I'm sure other people will be interested. But I can't say yes to everything 😌 I volunteer on a whole range of other projects. And my time is limited 😔

**Comment by Midnight-Cowboy** [comment]
I can solder, but I don't know how to program....

**Comment by londresarthur** [comment]
And I can program, but like Armel, I'm totally out of time at the moment. Ahh how much easier life would be if Fabrizio was part of the open source community.

**Comment by londresarthur** [comment]
Issue closed, maybe one day we will come together to implement new things. 73!

**Comment by wmarkow** [comment]
``` The information is not very clear: does this firmware support CW? In this case, pure CW, without modulation, just the carrier.

I think you can decode **CW** with **USB** demodulation mode. Just need to set the frequency i.e. around 700Hz below the frequency where **CW** is being transmitted, then you will hear a 700Hz tone of **CW**. 

If it goes about transmitting CW I have no idea; pressing PTT will generate carrier any way. You can check.
