### ISSUE TITLE
Changed behaviour of Exit button while channel scanning mode.

### ISSUE THREAD

**Issue by spamsool** [armel/uv-k5-firmware-custom#226]
Hi
I noticed that the behavior of Exit button has changed while it is in channels scanning mode.

Before - while radio was scanning channels - pressing Exit button once just stopped the scanning and that's all it did.

Now - Exit button has something like two modes in two cases:
1. When memory scanning is running but the screen is still backlit - pressing Exit stops the scan.
2. When memory scanning is running but the screen backlight timeout has already turned off the light - pressing Exit once only switches back on the backlight without stopping the scan and then only after second press of Exit it stops the scan.

Is it a expected feature? I may be wrong but I think it wasn't like this before.
Not a big deal but I just wanted to make sure.
Thanks

**Comment by armel** [comment]
Hello,

It was like this before. You can check with an older v2 version :)

Armel.
