### ISSUE TITLE
Txlock not working as expected

### ISSUE THREAD

**Issue by Linden1** [armel/uv-k5-firmware-custom#236]
I expected Txlock to work with any channel so went through my channels using chirp, locking any I don't want to risk TXing on. This setting is indeed changed and saved to file, yet once uploaded to the radio the setting is lost for channels other than AM - specifically airband as I have no other AM channels to test with. I can set some up if you need? The setting is again lost for my FM channels when changed on the actual radio as well.

**Comment by armel** [comment]
Trust me, it works.
What firmware version are you using? And what version of Chirp driver?

**Comment by Linden1** [comment]
3.3 with 3.3.0 driver.
Is it right that this setting won't function if "UNLOCK ALL" is selected?

**Comment by armel** [comment]
Yes of course.
**The FLock setting takes priority.** 
The right approach, if you're not a radio amateur, is to choose "DISABLE ALL" and then open exceptions on certain frequencies via TXLock.

**Comment by Linden1** [comment]
I see. Opposite way to what I expected from my experience of these radios so far, but makes total sense.
Thank you.
Closing

**Comment by armel** [comment]
Thank you 😌
