### ISSUE TITLE
Air Copy avec vérrouillage clavier actif

### ISSUE THREAD

**Issue by jdajdl** [armel/uv-k5-firmware-custom#244]
Bonjour,

Il semble impossible de déverrouiller le clavier en mode AirCopy, l'option vérrouillage clavier activée ne semble pas permettre l'utilisation de la fonction AirCopy.
Salutations
Julien

**Comment by armel** [comment]
[Fixé ](https://github.com/armel/uv-k5-firmware-custom/commit/26414b281189f4e20ac3baedf7d243dfc285b3ff)dans la prochaine release.
[Fixed ](https://github.com/armel/uv-k5-firmware-custom/commit/26414b281189f4e20ac3baedf7d243dfc285b3ff)in the next release.

Merci Julien.

Armel F4HWN.

**Comment by jdajdl** [comment]
Merci pour la qualité du soft !


Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
