### ISSUE TITLE
Possible to save frequencies found on spectrum analyser 

### ISSUE THREAD

**Issue by leelaa365** [armel/uv-k5-firmware-custom#250]
Is it possible to save/auto save to memory found spectrum analysis frequencys... Sorry if this sounds dumb new to custom FW

**Comment by armel** [comment]
Hello,

No, this is not planned.

Armel F4HWN

**Comment by leelaa365** [comment]
> Hello,
> 
> No, this is not planned.
> 
> Armel F4HWN

No problem thanks for the reply and firmware!
