### ISSUE TITLE
FM Radio

### ISSUE THREAD

**Issue by ricardoguimaraes2482** [armel/uv-k5-firmware-custom#267]
When I want to add a shortcut key to turn on FM Radio, this option does not exist in the menu. And when I try on chirp, it has the option, but then the radio doesn't recognize it. Am I doing something wrong or is it a bug?
Best regards.

**Comment by armel** [comment]
Hello,

Simple. You're probably using Banscope version. This version does not include FM braodcast. 

Armel F4HWN.

**Comment by ricardoguimaraes2482** [comment]
Before seeing your answer I already realized the error. Anyway, thanks for your quickness in helping.
Best regards.
