### ISSUE TITLE
Idée pour la 2.7

### ISSUE THREAD

**Issue by Chatdurail** [armel/uv-k5-firmware-custom#27]
Salut Armel, Alex 14UVR267 du groupe FB, 

J'espère que tu vas bien, 

J'aimerai savoir si il était possible de rajouter une option au menu 34 PonMSG : L'idée serait d'avoir le Sound de demarrage et les DEUX lignes de textes programmable dans CHIRP

Cela te semble t'il envisageable ? 

Bien à toi 

73'

**Comment by armel** [comment]
Hello :)

Comme j'avais un peu de place, ce sera implémenté dans la prochaine version. 
Je ferme l'issue.

Armel F4HWN.
