### ISSUE TITLE
RX mode doesn't save after changing it by press sidekey.

### ISSUE THREAD

**Issue by troilus** [armel/uv-k5-firmware-custom#278]
Hi, 
I don't know if it is a bug or by design, change the RX mode by using sidekey, the Rx mode seems dose not save,
after restarting the radio, it reverted to the state before the modifications.

**Comment by armel** [comment]
As many others actions. RX mode action is only for temporary change. In short, it's not a bug, it's a feature.
If you want a permanent change, use RxMode menu. 
Well, please, learn to use this radio before post issue.
