### ISSUE TITLE
BUG d'affichage : démarrage avec port USB de charge

### ISSUE THREAD

**Issue by fifisoft57** [armel/uv-k5-firmware-custom#28]
bonjour

j'ai remarque se soir, quand on démarre le K5 avec la prise  USB branche pour le charge, il y a le  même problème qu'avant avec des pixels a l'écran, je suis en version 2.5

avec l'option affichage complet et BIP au démarrage

cdt
Philippe

**Comment by armel** [comment]
Je pense définitivement que c'est un problème hardware. 
Il est difficile a reproduire et dépendant du niveau de batterie.
Dans tous les cas, il n'est pas bloquant.
Je ferme l'issue (même si je garde ce problème en tête, HI).

73'

Armel F4HWN.
