### ISSUE TITLE
Scan Issue on Quanshang UV-5R plus first channel in radio 

### ISSUE THREAD

**Issue by mlapalme99** [armel/uv-k5-firmware-custom#280]
It seem to go back to M01 every time in-betweens next mem in scan list ,EX. list of mems 1 through 5 scans like 1-1-1-2-1-3-1-4-1-5

**Comment by prokrypt** [comment]
Sounds like you enabled priority for M01 or something...

**Comment by armel** [comment]
Not me, but you :) So yes, it's because your channel 1 has been set as priority.

**Comment by armel** [comment]
Check this under Chirp...
![priority](https://github.com/user-attachments/assets/c3d7957f-08d5-435e-9a2a-853cae167010)

**Comment by mlapalme99** [comment]
Okay amazing I’ll try that
