### ISSUE TITLE
Set broadcast frequency range

### ISSUE THREAD

**Issue by Meckiilino** [armel/uv-k5-firmware-custom#296]
Hi,
i flashed fh4hwn mod 3.6 today. First time with Broadcast support.
Frequency range will be only 64-76M.
In Europe/Germany we will have 87.5-108M!

How to change it?

THX

**Comment by armel** [comment]
Hi,

Please, read the [documentation](https://github.com/armel/uv-k5-firmware-custom/wiki/FM-broadcast-radio-receiver#button-functions). In short, use long press on 1 Band key...

Armel F4HWN.

**Comment by Meckiilino** [comment]
THX for very quick support :-)
