### ISSUE TITLE
Scan doesn't continue after switch on

### ISSUE THREAD

**Issue by kocickamia** [armel/uv-k5-firmware-custom#304]
Hello Armel, I have mapped this function to a long press of the side button F1. If i start scanning by long pressing the "*" key, switch off then on the transceiver, then scanning continues. But not in case if i start scanning by long pressing the side button.

**Comment by armel** [comment]
Hello,

Thank you. That's correct. 
This problem has already been reported and will be [fixed](https://github.com/armel/uv-k5-firmware-custom/commit/4a892d867a2a7d73c0e3d88f392dbf93e3fc1ee7) in the next release. 

Armel F4HWN.

**Comment by armel** [comment]
Fixed in v3.7 😌
