### ISSUE TITLE
Wide/narrow bandwidth will not maintain after vfo switch in vfo mode

### ISSUE THREAD

**Issue by tufca** [armel/uv-k5-firmware-custom#312]
When made wide/narrow changes using side button (preset as s1long for example), then switch between vfo a and vfo b, the bandwidth state will not maintain but go back to the original state. If change bandwidth in the menu, then it will keep the state.

**Comment by armel** [comment]
Hi,

Normal use case. Shortcut use is for temporary change.

Armel F4HWN.
