### ISSUE TITLE
Request for a full feature version.

### ISSUE THREAD

**Issue by tufca** [armel/uv-k5-firmware-custom#314]
Since it's quite easy to get an official expanded eeprom version uvk6(512kb) from China, and easily expandable by stacking chips, I really hope you can release a full version of your fantastic firmware which includes both bandscope and broadcast feature, and possibly more in the future. Thank you and have a nice day.

**Comment by armel** [comment]
https://github.com/armel/uv-k5-firmware-custom/issues/144#issuecomment-2180382421
