### ISSUE TITLE
bug: Scanning channel lists changes the frequency of AirCopy function

### ISSUE THREAD

**Issue by wen24o2** [armel/uv-k5-firmware-custom#319]
Hi. When scanning channel lists, turning off the radio and turning it back on results in the scan resuming. And this is great. However, turning off the radio while scanning the channel lists and turning it on in AirCopy mode causes the radio in my case to constantly change the frequency, which should be set to 434,000 MHz.

**Comment by armel** [comment]
Hi and thank you. [Fixed](https://github.com/armel/uv-k5-firmware-custom/commit/dba1db3ea6cb1bad1203c19d3967bbf3f0438505) in next release.

**Comment by armel** [comment]
Fixed in v3.8. Thank you mate ;)
