### ISSUE TITLE
ZVEI selcall function.

### ISSUE THREAD

**Issue by baptistemichaud** [armel/uv-k5-firmware-custom#32]
Good morning,
I would like to make selective ZVEI calls as is possible with the IJV firmware, to trigger mountain rescue (REGA, Codis 74). I looked for the functionality in your documentation, but I couldn't find one, is there one in this firmware?

I wish you very good luck, and good luck for the rest of this improvement.

**Comment by armel** [comment]
Bonsoir,

Je pense qu'il n'y a pas suffisamment d'attente pour l'ajout de cette fonctionnalité. 
Je ne suis même pas sûr qu'elle soit envisageable. 
Je cloture cette issue mais je l'ouvrirais à nouveau si l'occasion se présente.

73'

Armel F4HWN.

**Comment by armel** [comment]
Won't fix

**Comment by armel** [comment]
Won't fix
