### ISSUE TITLE
Some wiki pages on RescueOps

### ISSUE THREAD

**Issue by emanuelegissi** [armel/uv-k5-firmware-custom#329]
Hi Armel,

I wrote a couple of wiki pages dedicated exclusively to the RescueOps version, according to our specific programming.
They are still draft quality.

Here they are:
https://github.com/emanuelegissi/uv-k5-firmware-custom/wiki

In particular, see the `using the radio` page.

May you be interested?

**Comment by armel** [comment]
Hi @emanuelegissi,

Of course I'm interested :)  I've added a [note](https://github.com/armel/uv-k5-firmware-custom/wiki/Radio-operation#usage) to the current documentation. Thank you very much.

Armel.
