### ISSUE TITLE
Feature request: Lock internal PTT but leave external PTT unlocked

### ISSUE THREAD

**Issue by Rayz224** [armel/uv-k5-firmware-custom#335]
Pretty much the title, for context, I have a radio chest pack that fits the UV-K5 but it's quite snug and it keeps pressure on the PTT so I was wondering if i could lock the internal PTT and only use an external one. 

From a quick look at the code (`driver/keyboard.h`) i'm not sure if it's possible as it seems the radio considers the internal and external PTT as the same key (`KEY_PTT`). Do you know if there's a way around that?

Merci!

**Comment by armel** [comment]
Hello,

In my opinion, this is not possible. Sorry.

Armel F4HWN.

**Comment by Rayz224** [comment]
No worries, that's the conclusion I was getting too.

Thank you
