### ISSUE TITLE
TX Lock

### ISSUE THREAD

**Issue by Rugged-ESP** [armel/uv-k5-firmware-custom#336]
Although the TX lock is activated in Chirp for some stored frequencies, it is still inactive on the UV-K5(8).
Unfortunately, moving to another memory location, retransmitting or changing the frequency does not change this situation.

**Comment by armel** [comment]
Which plan did you select in F Lock (hidden menus)... ?

**Comment by Rugged-ESP** [comment]
"CA HAM 144-148 430-450" is selected.
Does this setting overwrite the TX lock in Chirp?
It affects e.g. the frequencies 145.xxx, 147.xxx 
Thanks for the help

**Comment by armel** [comment]
Okay, then reread the [documentation](https://github.com/armel/uv-k5-firmware-custom/wiki/Radio-operation#about-the-flock-and-txlock-menus) if necessary. 

In a nutshell :

* In memory channel or VFO mode, if the frequency is **inside the band** plan selected in FLock, **you can transmit**.
* In memory channel or VFO mode, if the frequency is outside the band plan selected in FLock,
  * you can transmit only if TXLock is OFF
  * you cannot transmit if TXLock is ON

Armel F4HWN.

**Comment by Rugged-ESP** [comment]
Ok, thank you very much. Then I misunderstood the instructions.
