### ISSUE TITLE
Ver. 3.9 (RescueOps). Can't do scanning on NOAA channels?

### ISSUE THREAD

**Issue by simonforget** [armel/uv-k5-firmware-custom#343]
Hi,

While reviewing the NOAA channel functionality added to Ver. 3.9 (RescueOps), I (unsuccessfully) tried to scan the NOAA channels. Is it a bug or a feature? :-)

Note that Canada provides as well a radio weather service similar to the US.

Keep up your excellent work!

Simon Forget, VA2ESF

**Comment by armel** [comment]
Hi,

The NOAA feature works in the same way as on the Egzumer firmware. I can't improve it, as I can't test this feature (I live in France...).

Armel F4HWN.
