### ISSUE TITLE
ver3.9 bandscope Auto -Tx

### ISSUE THREAD

**Issue by marmatBCN** [armel/uv-k5-firmware-custom#345]
After uploading the new version, Tx turns on automatically at various moments, even when I'm in the MENU, the radio transmits by itself....?

**Comment by prokrypt** [comment]
Does it seem like vox? TX happens when you speak into the mic? 👀

**Comment by marmatBCN** [comment]
Yes, I checked and now it works like VOX

**Comment by marmatBCN** [comment]
I turned off VOX and it's ok

**Comment by armel** [comment]
Vox is a devil :)
@prokrypt is absolutely right :)

Armel
