### ISSUE TITLE
Switching to Broadcast FM while RX active will lock the keyboard

### ISSUE THREAD

**Issue by lapinos03** [armel/uv-k5-firmware-custom#55]
Hello !

I wanted to listen to Broadcast FM (keys F+0) while the radio was receiving a (continously transmitting) channel and it didn't switch to it. Actually the keyboard was locked while the display showed FM in the top left corner.

If the channel stops receiving then after a few seconds of silence, the radio switches to Broadcast FM and then you can handle the keys as normal. Otherwise the only solution is to power off/on (or to remove antenna to drop down the signal).

This happens when receiving on the TX channel only, whatever VFO-A or B.

Tested in bands 440 and 1200 MHz. Version 2.5. Reproductible anytime.

**Comment by prokrypt** [comment]
If anyone has this problem, just press EXIT.
